services:
  database:
    image: postgres:16-alpine
    container_name: melonela_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Montage de ton script d'initialisation pour créer les tables automatiquement
      - ./database/init:/docker-entrypoint-initdb.d
    
    # 🏎️ AJUSTEMENT DES COMMANDES POUR UNE CONSOMMATION RAM MINIMALE (OPTIMAL 8GB)
    command: >
      postgres
      -c max_connections=20
      -c shared_buffers=128MB
      -c work_mem=4MB
      -c maintenance_work_mem=32MB
      -c effective_cache_size=512MB
    
    # 🛑 SÉCURITÉ : Limite matérielle stricte imposée à Docker
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
    driver: local